apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jeanpool22/CI-CD'
    targetRevision: HEAD
    path: helm/microservice-hello
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservice-hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true