name: Construir y Desplegar Microservicios

on:
  push:
    branches:
      - main

jobs:
  construir:
    name: Construir imágenes Docker
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y publicar microservicio hello
        id: hello
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-hello
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservice-hello:latest

      - name: Construir y publicar microservicio goodbye
        id: goodbye
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-goodbye
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservice-goodbye:latest

  desplegar:
    name: Desplegar en Kubernetes
    runs-on: ubuntu-latest
    needs: construir

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar acceso al clúster Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Instalar Helm
        uses: azure/setup-helm@v3

      - name: Desplegar microservicio hello con Helm
        run: |
          helm upgrade --install hello-release helm/microservice-hello-chart/ --namespace default --create-namespace

      - name: Desplegar microservicio goodbye con Helm
        run: |
          helm upgrade --install goodbye-release helm/microservice-goodbye-chart/ --namespace default --create-namespace