name: Compilar y Desplegar

on:
  push:
    branches:
      - main

jobs:
  construir-y-desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Obtener SHA corto del commit
        id: variables
        run: echo "sha_corto=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Construir imagen microservice-hello
        run: |
          docker build -t jeandocker22/microservice-hello:${{ steps.variables.outputs.sha_corto }} ./microservice-hello

      - name: Subir imagen microservice-hello
        run: |
          docker push jeandocker22/microservice-hello:${{ steps.variables.outputs.sha_corto }}

      - name: Construir imagen microservice-goodbye
        run: |
          docker build -t jeandocker22/microservice-goodbye:${{ steps.variables.outputs.sha_corto }} ./microservice-goodbye

      - name: Subir imagen microservice-goodbye
        run: |
          docker push jeandocker22/microservice-goodbye:${{ steps.variables.outputs.sha_corto }}

      - name: Instalar yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Actualizar tag en values.yaml hello
        run: |
          yq -i '.image.tag = "${{ steps.variables.outputs.sha_corto }}"' helm/microservice-hello-chart/values.yaml

      - name: Actualizar tag en values.yaml goodbye
        run: |
          yq -i '.image.tag = "${{ steps.variables.outputs.sha_corto }}"' helm/microservice-goodbye-chart/values.yaml

      - name: Hacer commit y push de los cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/microservice-hello-chart/values.yaml helm/microservice-goodbye-chart/values.yaml
          git commit -m "Actualizar tags de imágenes a ${{ steps.variables.outputs.sha_corto }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/jeanpool22/CI-CD.git HEAD:main
