name: Construir y Desplegar Microservicios

on:
  push:
    branches:
      - main

jobs:
  construir:
    name: Construir imágenes Docker
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Establecer versión con timestamp
        id: version
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Construir y publicar microservicio hello
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-hello
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservice-hello:${{ env.VERSION }}

      - name: Construir y publicar microservicio goodbye
        uses: docker/build-push-action@v4
        with:
          context: ./microservice-goodbye
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservice-goodbye:${{ env.VERSION }}

      - name: Actualizar values.yaml de hello
        run: |
          sed -i "s|tag: .*|tag: \"${VERSION}\"|" helm/microservice-hello-chart/values.yaml

      - name: Actualizar values.yaml de goodbye
        run: |
          sed -i "s|tag: .*|tag: \"${VERSION}\"|" helm/microservice-goodbye-chart/values.yaml

      - name: Hacer commit de los cambios en los charts
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          export VERSION=${{ env.VERSION }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/microservice-hello-chart/values.yaml helm/microservice-goodbye-chart/values.yaml
          git commit -m "Actualizar tags de imagen a $VERSION" || echo "Sin cambios para commitear"
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git
          git push origin HEAD:main


